version: '3'
services:
  ruby:
    container_name: 'sample-ruby'
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt